# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 旅禾小栈
subtitle: '分享学识，分装快乐！'
description: '分享学识，分装快乐！凡吾所学、所思、所想、所感，均整理刊载至此，旅禾小栈静候你的光临（博客·文章·专栏·主页）'
keywords: 邱泉智,旅禾,旅禾小栈,旅禾Ryoine,文章,博客,blog,专栏,Qiu Quanzhi,主页
author: 旅禾Ryoine
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://home.qqzhi.cc
permalink: p/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: draft
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: 
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: 未归类
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: solitude
feed:
  enable: true
  type:
    - atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: /img/avatar.webp
  autodiscovery: true
  template:

markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: false
    langPrefix: 'language-'
    breaks: true
    linkify: true
    typographer: true
    quotes: '『』「」'
  enable_rules:
  disable_rules:
  plugins:
    - markdown-it-merge-cells
    - name: '@renbaoshuo/markdown-it-katex'
      options:
        skipDelimitersCheck: true
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: true
    permalinkClass: 'header-anchor'
    permalinkSide: 'right'
    permalinkSymbol: ''
    case: 0
    separator: '-'
  images:
    lazyload: true
    prepend_root: false
    post_asset: true
  inline: false  # https://markdown-it.github.io/markdown-it/#MarkdownIt.renderInline

post_wordcount:
  item_text: false
  wordcount: true
  min2read: false
  totalcount: true
  separated_meta: false

sitemap:
  path: sitemap.xml
  rel: true
  tags: false
  categories: false

abbrlink:
  alg: crc32  #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex

nofollow:
  enable: true
  field: post
  exclude:
    - 'www.qqzhi.cc'
    - 'home.qqzhi.cc'
    - 'app.qqzhi.cc'

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''