# ---------------------------
# Hexo Theme Solitude·改
# 原作者: 伍十七(@everfu)
# 原项目: https://github.com/everfu/hexo-theme-solitude
# 维护者: Ryoine(@Qiu-Quanzhi)
# 项目地址: https://github.com/Qiu-Quanzhi/hexo-theme-solitude-kai
# ---------------------------

# --------------------------- 开始 ---------------------------
# 网站信息
site:
  name:
    class: text
    custom: 旅禾小栈
  icon: /img/avatar.avif
  unified_title: 旅禾小站
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# 导航栏
nav:
  # 左侧按钮
  group:
    我的:
      个人主页: https://www.qqzhi.cc || /favicon.ico
      站点监测: https://stats.uptimerobot.com/0tX6TgfoLR || /img/icons/UptimeRobot.avif
      个人装备: /gear/ || /favicon.ico
      CanoKey: https://console.canokeys.org/ || /img/icons/CanoKey.avif

  # 菜单
  menu:
    首页: / || fas fa-house-chimney
    文库:
      文章合集: /archives/ || fas fa-folder-closed
      分类合集: /categories/ || fas fa-clone
      标签合集: /tags/ || fas fa-tags
    友链: /links/ || fas fa-user-group
    关于: /about/ || fas fa-image-portrait

  # 右侧按钮
  right:
    custom:
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# 侧边栏
aside:
  # 侧边栏配置

  # 值: about(信息卡), newestPost(最新文章), allInfo(网站信息)
  # Sticky: 固定位置 / noSticky: 不固定位置

  home:
    noSticky: "about"
    Sticky: "allInfo"
  post:
    noSticky: ""
    Sticky: "nav"
  page:
    noSticky: ""
    Sticky: ""
  # 菜单栏位置 (0: 左 1: 右)
  position: 1


  # 个人信息卡
  my_card:
    # 头像
    author:
      img: /img/avatar.avif
      url: https://www.qqzhi.cc/
    # 时段状态
    state:
      morning: ✨ 早上好，新的一天开始了
      noon: 🍃 午休时间
      afternoon: 🌞 下午好
      night: 🌙 晚上好，早点休息
      goodnight: 🔮 晚安
    # 交互语录
    witty_words:
      - 你一定可以的
      - 今天也要开心呀
      - 万事胜意
      - 好运气分你一半
      - 祝你好运

    # 更多链接
    information:
      个人主页: https://www.qqzhi.cc || fas fa-house-chimney
      Github: https://github.com/Qiu-Quanzhi || fab fa-github
      哔哩哔哩: https://space.bilibili.com/1036651852 || fab fa-bilibili
      电子邮箱: mailto:i@qqzhi.cc || far fa-envelope
  

  # 文章目录
  toc:
    post: true
    page: true
    vague: false
  

  # 标签
  tags:
    enable: true
    limit: 20
    # 推荐标签
    highlight_list:
  

  # 归档
  archive:
    enable: true
    type: "year"
  

  # 网站信息
  siteinfo:
    # 文章数量
    postcount: false
    # 总字数
    wordcount: true
    # 最后更新日期
    updatetime: true
    # 网站创建时间
    runtimeenable: true
    # 建站时间
    runtime: "2023-06-30 00:00:00"
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# 页面默认设置
page:
  # 404 页面
  error: true
  # 标签页面
  tags: true
  # 分类页面
  categories: true
  # 0: 排序列表 / 1: 跟随首页列表
  archives: 0
  # 默认值
  default:
    # 未设置封面时的默认图片
    cover:
      - /img/blog.avif
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# 文章设置
post:
  # 文章默认设置
  default:
    # 默认封面图片
    cover:
       # - /img/blog.avif
    # 默认位置
    loc: 地球
    # 默认版权
    copyright:
      enable: true
      author:
        url: /about/
        # 默认使用 site.icon
        img:
      # 默认许可证
      license: CC BY-NC-ND 4.0
      # 许可证链接
      licenseUrl: /copyright/
  

  # 文章元信息
  meta:
    # 发布日期
    date: true
    # 更新日期
    updated: true
    # 位置
    loc: true
    # 字数
    wordcount: true
  
  
  # 文章封面取色
  covercolor:
    enable: true
    # local: 本地取色 / api: API 取色 / ave: OSS 服务取色
    mode: local
    # API 地址
    api: # https://img2color.qqzhi.cc/api?img=
    # 缓存时间
    time: 43200000
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# 主题色
theme_color:
  dark: "#66ccff"
  light: "#66ccff"
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# 显示模式
display_mode:
  # auto: 自动切换（识别设备当前主题模式） / dark: 深色模式 / light: 浅色模式
  type: auto
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# 字体设定
font:
  # 全局字体
  font-size: 16px
  font-family: 'MiSans VF,MiSans,PingFang SC,Hiragino Sans GB,Microsoft YaHei,sans-serif'
  # 代码字体
  code-font-size: 16px
  code-font-family: 'ui-monospace,SFMono-Regular,"SF Mono",Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace'
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# Home page article configuration information
# 首页文章配置信息
index_post_list:
  length: 200
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# Mermaid
mermaid:
  enable: false
  per_page: false
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# Chart.js
chart:
  enable: false
  per_page: false
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# 控制台
console:
  enable: true
  card:
    # 标签
    tags: true
    # 归档
    archive: "year"
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# 页脚
footer:
  # 社交图标栏
  information:
    author: false
    left:
    right:
  


  # 页脚链接栏
  group:
    本站:
      版权声明: /copyright/
      个人主页: https://www.qqzhi.cc/
      个人装备: /gear/
    文库:
      文章合集: /archives/
      分类合集: /categories/
      标签合集: /tags/

  # 随机友链
  randomlink: true

  # 站点标注
  badge:
    - name: 粤ICP备2026090856号
      url: https://beian.miit.gov.cn/
    - name: 粤公网安备44098302441277号
      icon: /img/icons/police-emblem.avif
      url: https://beian.mps.gov.cn/#/query/webSearch?code=44098302441277

  # 页脚信息文字
  links:
    - name: 友链与鸣谢
      url: /links/
    - name: 订阅
      url: /atom.xml
    - name: 版权声明
      url: /copyright/
      icon:
        - fab fa-creative-commons
        - fab fa-creative-commons-by
        - fab fa-creative-commons-nc
        - fab fa-creative-commons-nd
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# 404 页面
errorpage:
  img: /img/404.avif
  text: 页面好像走丢了……
  recommendList: false
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# 图片懒加载
lazyload:
  enable: true
  # 启用范围: post / site
  field: site
  # 加载时占位图
  placeholder: ''
  # 加载失败占位图
  errorimg: /img/404.avif
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# 加载
loading:
  # 全屏加载
  fullpage: false
  # 加载图标，不写默认siteicon
  favicon: 
  # Pace 加载
  pace: true
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# 代码块高亮
highlight:
  enable: true
  # 当超过多少字时显示折叠按钮
  limit: 200
  # 是否启用复制按钮
  copy: true
  # 是否默认展开
  expand: true
  # 主题: default: 默认 / mac : 苹果终端
  theme: default
  # 颜色方案: default / solidity / dracula
  color: solidity
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# OpenGraph
OpenGraph:
  enable: true
  options:
    twitter_card: "summary_large_image"
    twitter_image: "https://home.qqzhi.cc/img/blog.avif"
    twitter_id: "@RyoineQ"
    twitter_site: "@RyoineQ"
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# 字数统计
# 警告: 请先安装 hexo-wordcount 插件。
wordcount: true
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# Katex
# Latex 公式支持
katex:
  enable: true
  # 是否在每个页面加载
  per_page: false
  # 是否启用复制公式
  copytex: true
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# 扩展
extends:
  # 插入到 head
  head:
    - <link rel="preconnect" href="https://npm.webcache.cn" crossorigin="anonymous">
    - <link rel="preconnect" href="https://cdnjs.webstatic.cn" crossorigin="anonymous">
    - <link rel="stylesheet" href="https://npm.webcache.cn/misans-vf@1.0.0/lib/MiSans.min.css" fetchpriority="high">
    - <link rel="icon" href="/favicon.ico">

  # 插入到 body
  body:
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# 日志
logs:
  enable: true
  home_mini: true
  page: /logs/
  style: 1
  strip: 30
# --------------------------- 结束 ---------------------------

# --------------------------- 开始 ---------------------------
# CDN配置
CDN:
  # CDN提供商配置
  internal: local # local / cdnjs / jsdelivr / unpkg / custom
  third_party: custom # cdnjs / jsdelivr / unpkg / custom
  # 是否使用版本号
  version: true
  # CDN 自定义链接格式
  custom_format: https://cdnjs.webstatic.cn/ajax/libs/${cdnjs_name}/${version}/${min_cdnjs_file}
  # 直接覆盖默认 CDN 链接（优先级最高）
  options:
    # chart_js:
    # color_thief:
    # fontawesome:
    # katex:
    # katex_copytex:
    # lazyload:
    # mermaid_js:
    # pace_js:
    # pjax:
    # swiper_css:
    # swiper_js:
# --------------------------- 结束 ---------------------------
