name: 自动构建并部署到自有服务器

on:
  push:
   branches:
     - main
  workflow_dispatch:   # 允许手动触发，方便首次测试

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取 main 分支最新代码
        uses: actions/checkout@v7.0.0
        with:
          ref: main

      - name: 安装 pnpm
        uses: pnpm/action-setup@v6.0.9

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: 构建
        run: pnpm build

      - name: 部署 dist 到自有服务器
        uses: easingthemes/ssh-deploy@v4
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT || '22' }}
          TARGET: ${{ secrets.REMOTE_PATH }}
